# Generated by Django 3.0.8 on 2020-07-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('location', models.CharField(max_length=225)),
                ('comment', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='comments')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pk']},
        ),
    ]
